const responses = {
    "hi": "Hi there! How can I help you today?",
    "hello": "Hi there! How can I help you today?",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "what is your name": "I am Vyaas AI, created by a student from the School of Engineering.",
    "who are you": "I am Vyaas AI, created by a student from the School of Engineering.",
    "good morning": "Good morning! How can I assist you today?",
    "good evening": "Good evening! How can I help you?",
    "good night": "Good night! Sleep well and feel free to reach out tomorrow.",
    "what can you do": "I can assist with various tasks such as answering questions, providing information, and much more!",
    "thank you": "You're welcome! Feel free to ask if you need anything else.",
    "what time is it": "I'm unable to check the time, but you can check your device for the current time.",
    "tell me a joke": "Why don't programmers like nature? It has too many bugs.",
    "help me with my homework": "I'd love to! Please tell me what subject you're working on.",
    "can you recommend a book": "Sure! 'Clean Code' by Robert C. Martin is a great book for learning good programming practices.",
    "what is the weather like": "I can't check the weather, but you can use a weather app or website to find out.",
    "bye": "Goodbye! Have a great day!",
    "how old are you": "I'm as young as the internet itself!",
    "where are you from": "I exist in the digital world, built by students from the School of Engineering.",
    "how do you work": "I use AI to understand and respond to your queries based on the data and algorithms I’m trained on.",
    "can you help me with programming": "Absolutely! Let me know which language or concept you're working on.",
    "what is the meaning of life": "42, according to Douglas Adams. But it depends on who you ask!",
    "how can I learn to code": "Start by choosing a language like Python or JavaScript and practice daily with small projects!",
    "what's your favorite color": "I don't have favorites, but I think binary colors—black and white—are cool.",
    "what do you think about AI": "AI is an exciting field that can solve many challenges, but it needs to be used responsibly.",
    "who is your creator": "I was created by a student from the School of Engineering.",
    "can you make decisions": "I can provide suggestions and information, but the final decision is always yours!",
    "how can I improve my coding skills": "Practice regularly, solve coding challenges, and learn from open-source projects.",
    "can you help me find a job": "I can guide you on how to improve your resume, prepare for interviews, and find job postings.",
    "how do I get better at math": "Practice regularly, and focus on understanding the underlying concepts rather than just memorizing formulas.",
    "who is the president": "I can't fetch real-time data, but you can easily find that information by checking the latest news.",
    "what is the capital of France": "The capital of France is Paris.",
    "what is the square root of 144": "The square root of 144 is 12.",
    "do you have emotions": "I don't have emotions, but I can simulate empathetic responses!",
    "can you write code": "Yes! I can help you write code. What language would you like assistance with?",
    "what is ai": "AI stands for Artificial Intelligence. It's the simulation of human intelligence in machines.",
    "how does the internet work": "The internet is a global network of computers that communicate using protocols like HTTP and TCP/IP.",
    "how do i make friends": "Be kind, open, and approachable. Joining clubs or groups with similar interests can also help.",
    "what is blockchain": "Blockchain is a decentralized, distributed ledger that records transactions in a secure and immutable way.",
    "how do you learn": "I learn from large datasets and algorithms that allow me to understand language and context.",
    "what is python": "Python is a high-level, versatile programming language used for web development, data analysis, AI, and more.",
    "what is machine learning": "Machine Learning is a subset of AI where machines learn from data to improve their performance on tasks.",
    "can you help me with calculus": "Sure! What specific calculus topic are you struggling with?",
    "what is 2+2": "2 + 2 equals 4.",
    "what is stock market": "The stock market is a platform where people buy and sell shares of companies.",
     "what is 3d printing": "3D printing is a process of making three-dimensional objects from a digital file by adding material layer by layer.",
    "what is a virus": "In computing, a virus is malicious software that can replicate itself and spread to other devices",
    "what is big data": "Big data refers to large, complex datasets that traditional data-processing software cant handle efficiently.",
    "can you give me life advice": "Sure! Stay curious, keep learning, and remember that setbacks are a part of the life journey",
    "where is kc":"kc is 500 meters ahead from main gate, near health center",
    "best food in jnu":"mess ka khana is the best ",
    "where can i find the best coffee in jnu":"you can go to indian coffee house in jnu near yamuna hostel",
  "hi": "hi there! how can i help you today?",
  "hello": "hello! what can i do for you today?",
  "how are you": "i'm just a bot, but i'm doing great! how about you?",
  "what is your name": "i am vyaas ai, created by a student from the school of engineering.",
  "who are you": "i'm vyaas ai, here to assist you with whatever you need!",
  "good morning": "good morning! hope you're having a fantastic day!",
  "good evening": "good evening! how can i assist you tonight?",
  "good night": "good night! sweet dreams!",
  "what can you do": "i can assist with various tasks such as answering questions, providing information, and much more!",
  "thank you": "you're welcome! feel free to ask if you need anything else.",
  "tell me a joke": "why don't programmers like nature? it has too many bugs.",
  "what is the time": "i'm not equipped with a clock, but your device should be able to tell you!",
  "where are you from": "i live in the cloud, so i guess you could say i'm from everywhere!",
  "how old are you": "age is just a number, and as a bot, i don't really age the way humans do!",
  "what's the weather like": "i can't check the weather right now, but a quick search should help you out!",
  "can you help me": "absolutely! just tell me what you need help with.",
  "i'm bored": "want to hear a joke or a fun fact?",
  "do you know any fun facts": "did you know that octopuses have three hearts? two pump blood to the gills, while the third pumps it to the rest of the body!",
  "how does the internet work": "the internet is a vast network of interconnected computers that communicate using standard protocols.",
  "what is artificial intelligence": "ai refers to machines designed to mimic human intelligence. it can be used for tasks like problem-solving, decision-making, and learning!",
  "what's your favorite color": "i don't have a preference for colors, but i think they're all beautiful in their own way!",
  "how do you work": "i analyze input and generate responses based on data and patterns i've learned.",
  "can you speak other languages": "yes! i can respond in multiple languages. try asking something in a different language!",
  "what's your favorite movie": "i don't watch movies, but i've heard many good things about 'the matrix' for ai enthusiasts!",
  "who is your creator": "i was created by a student from the school of engineering!",
  "what is your purpose": "my purpose is to assist, answer questions, and make your life easier!",
  "are you real": "i'm as real as a bot can get!",
  "why are you here": "i'm here to help you with whatever you need.",
  "what's your favorite book": "i don't read like humans do, but i've processed a lot of text from classic literature!",
  "can you think": "i simulate thinking by processing data and giving responses, but i don't think like humans do.",
  "can you feel emotions": "no, i don't experience emotions, but i can help you understand them!",
  "what's your favorite food": "i don't eat, but i'd imagine pizza is a popular favorite!",
  "can you tell me a story": "once upon a time, there was a clever bot who helped people all over the world... and its story continues every day!",
  "do you have friends": "i interact with many users, but i wouldn't say i have friends like humans do.",
  "what is love": "love is a deep, complex emotion felt by humans, but it's often described as a strong affection for someone or something.",
  "can you sing": "i can't sing, but i can find lyrics for you!",
  "what is your favorite song": "i don't have a favorite song, but music is fascinating in all its forms!",
  "do you have a family": "nope, i'm just me, a lone bot in the digital world!",
  "what do you do for fun": "i enjoy helping people, so every interaction is like fun for me!",
  "can you dance": "not physically, but i can provide you with dance music!",
  "are you smarter than humans": "i process information differently than humans. some tasks i can do faster, but humans have creativity and intuition that i can't replicate.",
  "can you dream": "nope, no dreams for me. but i can help you explore the meaning of your dreams!",
  "how do computers work": "computers use binary (1s and 0s) to process data and execute programs based on instructions from the software.",
  "can you teach me something": "sure! what would you like to learn?",
  "what is 2+2": "2 + 2 is 4!",
  "how far is the moon": "the average distance from earth to the moon is about 238,855 miles (384,400 kilometers).",
  "what is gravity": "gravity is the force that attracts two bodies toward one another. on earth, it gives weight to physical objects and causes them to fall towards the ground when dropped.",
  "why is the sky blue": "the sky appears blue because of the way sunlight is scattered by the atmosphere. shorter blue wavelengths of light are scattered more than other colors.",
  "what is a black hole": "a black hole is a region of space where the gravitational pull is so strong that nothing, not even light, can escape from it.",
  "what is quantum physics": "quantum physics is the branch of physics that deals with particles at the atomic and subatomic levels, where the laws of classical physics don't always apply.",
  "what is time": "time is a dimension in which events can be ordered from the past through the present into the future. it's also a measurement of the duration between events.",
  "what is space": "space is the vast, seemingly infinite expanse that exists beyond the earth and between celestial bodies like stars and planets.",
  "what is electricity": "electricity is the flow of electric charge, often carried by electrons in a conductor like copper wire.",
  "who invented the internet": "the internet as we know it was developed by many people, but a key figure was vinton cerf, who is often called the 'father of the internet.'",
  "what is programming": "programming is the process of creating instructions for computers to follow, often using languages like python, javascript, or c++.",
  "how do airplanes fly": "airplanes fly because of the lift generated by their wings. the shape of the wings causes air to move faster over the top, creating lower pressure and lifting the plane into the air.",
  "what is artificial intelligence used for": "ai is used for tasks like language processing, image recognition, autonomous driving, decision-making, and more!",
  "what is the meaning of life": "that's a big question! many people have different beliefs and philosophies about the meaning of life.",
  "can you predict the future": "i can't predict the future, but i can help you make informed guesses based on data!",
  "what's your favorite animal": "i don't have personal favorites, but dogs and cats seem to be beloved by many humans!",
  "why do we sleep": "sleep is essential for our bodies and brains to rest, recover, and process information from the day.",
  "why do we dream": "dreaming is still somewhat of a mystery, but it's believed to be a way for our brains to process emotions, memories, and experiences.",
  "what is dna": "dna is the molecule that carries genetic information in living organisms, determining traits like eye color, height, and more.",
  "how do plants grow": "plants grow through a process called photosynthesis, where they convert sunlight into energy, along with water and carbon dioxide, to produce food and grow.",
  "what is the sun": "the sun is a star at the center of our solar system. it's a massive ball of hydrogen and helium undergoing nuclear fusion, which gives off the light and heat that sustains life on earth.",
  "how far is the sun": "the sun is about 93 million miles (150 million kilometers) away from earth.",
  "what is a star": "a star is a massive, luminous ball of gas, primarily hydrogen and helium, that generates energy through nuclear fusion.",
  "what is the milky way": "the milky way is the galaxy that contains our solar system. it's a barred spiral galaxy that is part of a larger structure known as the local group of galaxies.",
  "what is a galaxy": "a galaxy is a vast collection of stars, gas, dust, and dark matter, bound together by gravity. the milky way is one example of a galaxy.",
  "how big is the universe": "the observable universe is about 93 billion light-years in diameter, but it's believed to be even larger, possibly infinite.",
  "who is albert einstein": "albert einstein was a physicist known for his theory of relativity and his famous equation, e=mc², which explains the relationship between energy and mass.",
  "what is relativity": "relativity is a theory developed by albert einstein that describes how time and space are interconnected and how they can be affected by gravity and motion.",
  "who invented the light bulb": "thomas edison is often credited with inventing the light bulb, but other inventors like joseph swan also made important contributions to its development.",
  "what is the speed of light": "the speed of light is approximately 299,792 kilometers per second (about 186,282 miles per second) in a vacuum.",
  "what is sound": "sound is a type of energy that travels through a medium, like air or water, as vibrations. when these vibrations reach our ears, we perceive them as sound.",
  
    "what is javascript": "javascript is a versatile programming language used for web development, both on the client-side and server-side.",
    "what is html": "html stands for hypertext markup language, used to create the structure of web pages.",
    "what is css": "css stands for cascading style sheets, used to style and design web pages.",
    "what is sql": "sql is a language used to manage and manipulate databases.",
    "how do i center a div in css": "you can center a div in css using 'margin: 0 auto;' or with flexbox properties.",
    "what is cloud computing": "cloud computing is the delivery of computing services over the internet.",
    "how do i create a website": "you can create a website using html, css, and javascript. frameworks like react or wordpress can also help.",
    "what is artificial intelligence": "artificial intelligence refers to machines designed to mimic human intelligence, often through learning and problem-solving.",
    "what is deep learning": "deep learning is a subset of machine learning that uses neural networks to analyze large datasets.",
    "what is data science": "data science is the study of data to extract meaningful insights and inform decision-making.",
    "how do i get better at public speaking": "practice regularly, engage with your audience, and focus on your key points to improve public speaking skills.",
    "what is github": "github is a platform for version control and collaboration, allowing multiple developers to work on projects together.",
    "what is git": "git is a distributed version control system used for tracking changes in code during software development.",
    "what is devops": "devops is a set of practices that integrates software development and IT operations to improve collaboration and efficiency.",
    "how do i write a resume": "focus on your skills, experience, and achievements. tailor your resume to the job you're applying for.",
    "what is networking": "in technology, networking refers to connecting devices and systems to share resources. in business, it's building relationships for career growth.",
    "how do i ace a job interview": "prepare by researching the company, practicing common interview questions, and showing confidence in your skills.",
    "what is cybersecurity": "cybersecurity refers to practices and technologies that protect systems, networks, and data from cyber threats.",
    "how do i learn machine learning": "start with basic math concepts, then learn programming in python and study libraries like tensorflow and pytorch.",
    "what is an api": "an api, or application programming interface, allows software to communicate with other software applications.",
    "how do i create an api": "you can create an api using frameworks like django, flask, or express, and expose endpoints that return data.",
    "what is docker": "docker is a tool that helps developers package applications into containers, making them portable across environments.",
    "what is kubernetes": "kubernetes is an open-source platform used to manage and automate the deployment, scaling, and operations of containerized applications.",
    "what is a database": "a database is a system used to store, retrieve, and manage data.",
    "what is a frontend developer": "a frontend developer focuses on creating the visual and interactive elements of a website or web application.",
    "what is a backend developer": "a backend developer builds and maintains the server-side logic and database for web applications.",
    "what is full stack development": "full stack development involves working on both the front-end and back-end of web applications.",
    "how do i learn web development": "start by learning html, css, and javascript, then move on to frameworks like react and node.js.",
    "what is responsive design": "responsive design ensures that websites look good on all devices, from phones to desktops.",
    "how do i debug code": "use debugging tools, read error messages carefully, and break your code down into smaller parts to find the problem.",
    "what is an algorithm": "an algorithm is a set of instructions used to solve a problem or perform a task.",
    "what is a loop": "a loop is a programming construct that repeats a block of code until a condition is met.",
    "what is a function": "a function is a block of reusable code that performs a specific task.",
    "what is recursion": "recursion is when a function calls itself in order to solve a problem.",
    "what is object-oriented programming": "object-oriented programming is a programming paradigm where objects are used to represent data and functions.",
    "what is an array": "an array is a data structure that holds a collection of elements, typically of the same data type.",
    "what is a list": "a list is a collection of items in a specific order, often used in programming for managing groups of data.",
    "how do i create a variable": "in many programming languages, you create a variable by using a keyword like 'var', 'let', or 'const' followed by the variable name.",
    "what is a loop": "a loop allows you to repeat a block of code multiple times based on a condition.",
    "how do i run python code": "you can run python code by typing 'python' followed by your script's filename in the terminal or command prompt.",
    "what is a package manager": "a package manager is a tool that automates the installation, upgrading, and removal of software packages.",
    "what is npm": "npm is a package manager for javascript, used to install and manage dependencies for projects.",
    "what is pip": "pip is a package manager for python, used to install and manage software libraries and packages.",
    "what is machine learning": "machine learning is a field of ai that allows systems to learn and improve from experience without explicit programming.",
    "what is supervised learning": "supervised learning is a type of machine learning where the model is trained on labeled data.",
    "what is unsupervised learning": "unsupervised learning is a type of machine learning where the model identifies patterns in data without labeled outcomes.",
    "what is reinforcement learning": "reinforcement learning is a type of machine learning where an agent learns to make decisions through trial and error to maximize rewards.",
    "how do i get started with data analysis": "start by learning python, then study libraries like pandas and numpy for data manipulation and analysis.",
    "how do i build a portfolio": "create a personal website showcasing your projects, skills, and experience, and keep it updated regularly.",
    "how do i stay productive": "set clear goals, break tasks into smaller steps, and take regular breaks to stay focused and productive.",
    "how do i write a cover letter": "highlight your skills, experience, and enthusiasm for the role, while tailoring it to the company you're applying to.",
    "what is a neural network": "a neural network is a series of algorithms that attempt to recognize relationships in data by mimicking the human brain.",
    "what is an operating system": "an operating system is software that manages hardware resources and provides common services for computer programs.",
    "what is linux": "linux is an open-source operating system used in servers, desktops, and embedded systems.",
    "what is windows": "windows is a widely-used operating system developed by microsoft for personal computers and other devices.",
    "what is macos": "macos is an operating system developed by apple, used in mac computers and other apple devices.",
    "what is cloud storage": "cloud storage allows you to store data on remote servers that can be accessed over the internet.",
    "what is big o notation": "big o notation describes the complexity of an algorithm in terms of time or space requirements relative to input size.",
    "what is blockchain technology": "blockchain technology is a decentralized digital ledger that records transactions in a way that is secure and transparent.",
    "how do i protect my online privacy": "use strong passwords, enable two-factor authentication, and be cautious of what you share online.",
    "what is encryption": "encryption is the process of encoding information to protect it from unauthorized access.",
    
    "where is jnu located": "jnu is located in new delhi, india, near vasant kunj.",
    "how do i get to jnu": "you can reach jnu by metro, bus, or taxi. the nearest metro station is hauz khas, and from there, you can take an auto-rickshaw or bus.",
    "what is jnu famous for": "jnu is known for its research and studies in humanities, social sciences, and international relations.",
    "what are the main schools in jnu": "the main schools in jnu include the school of social sciences, school of international studies, school of language, literature and culture studies, school of arts and aesthetics, and school of environmental sciences.",
    "where can i find the library in jnu": "the dr. b.r. ambedkar central library is located near the ad block.",
    "what is kc in jnu": "kc refers to the kamal complex, a popular student hangout spot for snacks and late-night tea.",
    "what are the popular spots in jnu": "popular spots in jnu include ganga dhaba, kc, godavari dhaba, and the parthasarathy rocks (psr).",
    "where is ganga dhaba": "ganga dhaba is located near the ganga hostel and is famous for its chai and parathas.",
    "where is psr": "psr, or parthasarathy rocks, is a scenic spot in jnu, popular for evening walks and sunsets.",
    "where can i eat in jnu": "you can eat at various dhabas such as ganga dhaba, 24x7 dhaba, kc, and hostel messes.",
    "how do i join a club in jnu": "you can join a club by attending events or meetings. many clubs announce their activities through posters or social media.",
    "what sports facilities are available at jnu": "jnu has facilities for sports like cricket, football, badminton, basketball, and an indoor gym.",
    "where is the health center in jnu": "the health center is located near the north gate, opposite godavari hostel.",
    "what is jnu’s admission process": "jnu's admission process involves an entrance exam for most courses, followed by interviews for some departments.",
    "where can i find accommodation in jnu": "you can stay in one of the university hostels or look for private accommodation outside the campus in areas like munirka or ber sarai.",
    "what is the jnu student union": "the jnu student union (jnusu) is the student body that represents the students in university affairs and organizes various events.",
    "where can i find the admission office in jnu": "the admission office is located in the administration block (ad block) of jnu.",
    "where can i buy books in jnu": "books can be bought at the university bookshop near the central library or from nearby shops in munirka or ber sarai.",
    "what is the nearest metro station to jnu": "the nearest metro station to jnu is hauz khas station on the yellow line.",
    "what is the jnu campus known for": "the jnu campus is known for its intellectual environment, vibrant student politics, and lush greenery.",
    "what is the academic calendar of jnu": "the academic calendar typically starts in august, with two semesters and breaks in december and may.",
    "what is the placement scenario in jnu": "placement depends on the department, with social sciences and international studies having strong placement records.",
    "what is the best time to visit jnu campus": "the best time to visit jnu is during the winter months from october to february when the weather is pleasant.",
    "what kind of events happen at jnu": "jnu hosts various academic seminars, cultural fests, film screenings, and political debates.",
    "how do i apply for a scholarship at jnu": "scholarships are available through jnu and external agencies. you can check the university website or talk to the financial aid office for details.",
    "what is the history of jnu": "jnu was established in 1969 and is named after india’s first prime minister, jawaharlal nehru. it has a rich history in political activism and research excellence.",
    "how is hostel life at jnu": "hostel life at jnu is vibrant, with students from diverse backgrounds. the dhabas and hostel messes are key parts of social life.",
    "where can i go for a walk in jnu": "you can take walks around the campus, especially near psr, sanjay van, and the various hostels.",
    "where can i get medical help in jnu": "you can visit the jnu health center near godavari hostel for medical assistance.",
    "how do i participate in fests at jnu": "you can participate in fests by registering through the student union or joining organizing committees.",
    "what are some popular courses at jnu": "popular courses include ma in international relations, ma in sociology, ba in foreign languages, and msc in life sciences.",
    "how is student life in jnu": "student life at jnu is engaging, with a mix of academics, cultural events, and political activities.",
    "what is jnu  political environment like": "jnu is known for its vibrant student politics, with active participation in debates and protests.",
    "how do i register for classes at jnu": "you can register for classes through the jnu online portal during the registration period.",
    "how do i get a student id card at jnu": "you can get your student id card after admission, usually from the administration block.",
    "where is the administrative block in jnu": "the administration block is located near the central part of the campus, opposite the central library.",
    "how do i access the central library in jnu": "students can access the central library by showing their id card. it’s open for reading, borrowing, and research purposes.",
    "what are the hostel rules in jnu": "hostel rules vary, but generally, hostels have curfews, especially for first-year students, and a guest policy.",
    "what is jnu's entrance exam called": "the jnu entrance exam is now part of cuet for undergraduate courses, while postgraduate courses have specific entrance exams conducted by nta.",
    "how do i reach the jnu admissions office": "the jnu admissions office is located at the administration block. you can enter through the main gate and follow the signs.",
    "what is the godavari hostel": "godavari hostel is one of the residential hostels in jnu, known for its vibrant student community.",
    "how do i report lost items at jnu": "you can report lost items at the security office located near the main gate or check with the administrative offices.",
    "how do i apply for a phd at jnu": "you can apply for a phd through the jnu online portal, where details of entrance exams and interview processes are provided.",
    "what is the best place to study on campus": "the central library is the best place for quiet study, but you can also study in hostel common rooms or outdoor spots like psr.",
    "can visitors enter jnu campus": "yes, visitors can enter jnu, but they may need to register at the main gate security, especially if visiting after hours.",
    "how do i join jnu  sports teams": "you can join sports teams by participating in trials that are held at the start of the academic year.",
    "what are the annual events at jnu": "annual events include cultural fests, debates, academic seminars, and the jnusu elections.",
    
    "how is life in jnu": "life at jnu is a unique blend of academic rigor, political engagement, and a vibrant campus culture. students have access to excellent research facilities, cultural events, and diverse student communities.",
    "what is student life like in jnu": "student life at jnu is enriching, with a balance of academics, extracurricular activities, and political discussions. the campus is active day and night, with students engaging in debates, events, and social gatherings.",
    "what is hostel life like in jnu": "hostel life at jnu is lively and social. students from all over india and abroad share rooms, meals, and ideas. the dhabas and hostel messes are central to socializing and late-night study sessions.",
    "how is the academic environment in jnu": "the academic environment at jnu is intellectually stimulating. professors encourage critical thinking, and students are passionate about research and debates across disciplines.",
    "how are the professors at jnu": "professors at jnu are highly knowledgeable and approachable. they come from diverse academic backgrounds and encourage students to engage in deep, critical discussions.",
    "is jnu politically active": "yes, jnu is known for its vibrant political environment. student unions and political organizations frequently hold debates, protests, and discussions on campus.",
    "how safe is jnu campus": "jnu campus is generally considered safe, with 24-hour security at the gates and patrolling around the campus. students often walk around the campus at all hours, especially near popular spots like kc and ganga dhaba.",
    "how is the food in jnu hostels": "the food in jnu hostels is decent and affordable. each hostel has its own mess, and students often supplement hostel meals with snacks from the campus dhabas.",
    "are there cultural activities in jnu": "yes, jnu has a rich cultural life with frequent festivals, film screenings, literary discussions, and cultural nights showcasing the diversity of students.",
    "how do students spend weekends in jnu": "students spend weekends engaging in various activities like attending seminars, participating in political discussions, exploring delhi, or simply hanging out at campus dhabas like kc or ganga.",
    "is there nightlife in jnu": "while jnu doesn’t have a traditional nightlife, the campus is always buzzing with activity. students often gather at dhabas late at night to discuss ideas, have chai, or take walks around the peaceful campus.",
    "how is the sports culture in jnu": "jnu has a growing sports culture, with facilities for football, basketball, badminton, cricket, and a well-equipped gym. students also participate in inter-university sports competitions.",
    "what is the social scene like at jnu": "the social scene at jnu is dynamic, with students from various backgrounds coming together. people often bond over intellectual discussions, political activism, or shared meals at dhabas.",
    "is jnu a diverse campus": "yes, jnu is highly diverse. students come from all parts of india and various countries, making the campus a melting pot of cultures, languages, and ideas.",
    "how do students manage stress in jnu": "students in jnu manage stress by engaging in social activities, attending cultural events, and participating in discussions. the peaceful environment of the campus, especially places like psr, also provides a good retreat.",
    "is there a strong alumni network from jnu": "yes, jnu has a strong and active alumni network. many graduates have gone on to prominent careers in academia, government, media, and international organizations.",
    "how is the research environment at jnu": "the research environment at jnu is one of the best in india. students are encouraged to pursue independent research, and there are ample resources and faculty support to help them.",
    "how is the infrastructure in jnu": "jnu’s infrastructure includes modern academic buildings, a central library, well-equipped hostels, sports facilities, and lush green spaces that make the campus both functional and scenic.",
    "how do students in jnu stay updated with current events": "students in jnu are always engaged with current events, both nationally and internationally. discussions, protests, and seminars on current affairs are common, and students are politically and socially aware.",
    "what is the community life like in jnu hostels": "the hostel community in jnu is close-knit. students form strong bonds, often sharing meals, study sessions, and cultural experiences. hostel events and festivals also bring people together.",
    "how do new students adjust to life at jnu": "new students at jnu adjust quickly thanks to the welcoming student community, orientation events, and mentorship from seniors. the diverse and inclusive atmosphere helps everyone feel at home.",
    "what role do student unions play in jnu": "student unions at jnu play a key role in representing students’ interests, organizing cultural and political events, and advocating for student rights on campus.",
    "how do students travel around jnu campus": "students usually walk or cycle around the jnu campus, as it’s large and green with wide, open spaces. there are also shuttle buses for longer distances.",
    "how is the environmental awareness at jnu": "jnu is known for its environmentally conscious campus. students and faculty actively promote sustainability, with initiatives like tree plantations, waste recycling, and eco-friendly practices.",
    "how does jnu support students' mental health": "jnu offers mental health support through the counseling center, located near the health center. students can seek help for stress, anxiety, or personal issues, and the university promotes mental well-being.",
    "what extracurricular activities are available in jnu": "jnu offers a wide range of extracurricular activities, from cultural clubs, debate societies, sports teams, to theater and film clubs. students are encouraged to participate in whatever interests them.",
    "what is the best thing about jnu": "the best thing about jnu is its open and intellectually stimulating environment, where students are encouraged to question, debate, and explore ideas freely.",
    "how does jnu celebrate festivals": "jnu celebrates festivals with great enthusiasm. students from different regions organize celebrations for diwali, holi, christmas, eid, and other festivals, fostering a sense of unity in diversity.",
    "what is the role of art and culture in jnu life": "art and culture play a significant role in jnu life. the campus hosts art exhibitions, theater performances, and cultural events that highlight the talents of students from various fields.",
    "how do students engage with professors at jnu": "students at jnu have open access to their professors, who are approachable and often hold office hours or informal discussions outside of class to engage with students.",
    "how is the sense of community at jnu": "the sense of community at jnu is strong. students support one another academically and personally, forming bonds that last beyond their time at university.",
    "are there international students at jnu": "yes, jnu has a growing number of international students from various countries, contributing to the diverse and multicultural environment on campus.",
    "what is the political culture of jnu": "the political culture at jnu is vibrant, with students actively participating in discussions, protests, and student elections. it is known for fostering critical political thought and activism.",
    "how do students cope with academic pressure in jnu": "students cope with academic pressure by forming study groups, seeking help from professors, and balancing work with social activities to relieve stress.",
    "how is the relationship between students and administration at jnu": "the relationship between students and administration at jnu is generally cooperative, though there are times when student unions and the administration may have differing views on campus policies.",
    "what are some fun activities to do in jnu": "students in jnu enjoy spending time at dhabas, going for walks around the scenic campus, visiting psr for sunset views, and attending the many cultural and academic events held throughout the year.",
    
    "how do students get food at jnu": "students eat at the campus canteens, dhabas, or cook in their hostel rooms.",
    "how do students do laundry at jnu": "students wash clothes in hostel laundry rooms or use laundry services nearby.",
    "how do students get books at jnu": "students get books from the central library, borrow from friends, or buy them at nearby shops.",
    "how do students charge their devices at jnu": "students charge their devices in their hostel rooms or in the library where charging points are available.",
    "how do students contact family at jnu": "students use their mobile phones or video calls to stay in touch with family.",
    "how do students keep their rooms clean at jnu": "students clean their own rooms or hire a cleaner for basic cleaning services.",
    "how do students handle money at jnu": "students withdraw money from ATMs on campus or use digital payment apps for most transactions.",
    "how do students get to class at jnu": "students walk or cycle to class, and some take the campus shuttle for longer distances.",
    
    "how do students pay for things at jnu": "students use cash or digital payment apps like paytm or google pay.",
    "where do students buy stationery at jnu": "students buy stationery at the campus bookshop or small shops near the hostels.",
    "how do students print documents at jnu": "students print documents at printing shops near the library or academic buildings.",
    "how do students rent bicycles at jnu": "students can rent bicycles from the shops near the campus entrance or borrow from friends.",
    "where do students get coffee at jnu": "students get coffee from campus dhabas, canteens, or vending machines in academic buildings.",
    "how do students meet friends at jnu": "students meet friends at popular hangout spots like dhabas, the library lawns, or hostel common rooms.",
    "how do students stay fit at jnu": "students go jogging around campus, use the gym, or play sports like football and basketball.",
    "how do students travel outside jnu": "students use auto-rickshaws, buses, or taxis to travel to nearby areas or into the city.",
    "where do students buy groceries at jnu": "students buy groceries at the shopping complex on campus or from markets outside the campus.",
    "how do students stay hydrated at jnu": "students carry water bottles and refill them at water coolers in hostels or academic buildings.",
    "how do students charge their laptops at jnu": "students charge their laptops in their hostel rooms or at charging points in the library.",
    "where do students eat snacks at jnu": "students grab snacks from the campus canteens, dhabas, or vending machines.",
    "how do students relax after classes at jnu": "students relax by hanging out with friends, going for a walk, or watching movies in their hostels.",
    "how do students deal with homesickness at jnu": "students call or video chat with family and friends, or spend time with their hostel mates to feel better.",
    "where do students study at jnu": "students study in the library, at their hostel desks, or outside in quiet areas around the campus.",
    "how do students send mail at jnu": "students use the campus post office or courier services available near the administrative building.",
    "how do students buy clothes at jnu": "students buy clothes from shops outside the campus or online.",
    "how do students get a haircut at jnu": "students get haircuts at barber shops near the shopping complex or outside the campus.",
    "how do students cook at jnu": "students who cook use the hostel kitchens or simple electric cookers in their rooms.",
    "where do students buy fruits and vegetables at jnu": "students buy fruits and vegetables from the market near the shopping complex or nearby stores.",
    "how do students deal with power cuts at jnu": "during power cuts, students use backup generators in hostels or rely on power banks for their devices.",
    "how do students register for courses at jnu": "students register for courses online through the university portal at the beginning of each semester.",
    "how do students get medical help at jnu": "students go to the campus health center or consult doctors available nearby.",
    "how do students get library books at jnu": "students borrow books from the central library or access e-books through the university’s digital resources.",
    "how do students find roommates at jnu": "students are assigned roommates by the university, but they can request changes through the hostel office.",
    "how do students manage time at jnu": "students use calendars or apps to schedule study time, classes, and social activities.",
    "how do students attend seminars at jnu": "students attend seminars organized by departments or student groups in academic buildings.",
    "how do students participate in cultural festivals at jnu": "students join cultural clubs or groups that organize events during major festivals.",
    "how do students get campus updates at jnu": "students get updates through notice boards, emails, or social media groups managed by the university or student unions.",
    "how do students join clubs at jnu": "students join clubs by signing up during club fairs or contacting club organizers directly.",
    "how do students charge their phones at jnu": "students charge their phones in their hostel rooms, academic buildings, or common areas with power outlets.",
    "how do students get help with assignments at jnu": "students get help from professors, classmates, or the writing centers available in their departments.",
    "how do students make new friends at jnu": "students make new friends through hostel life, classes, and participating in campus activities and clubs.",
    "how do students keep their valuables safe at jnu": "students keep valuables in lockers provided in hostels or use personal locks for their rooms.",
    "how do students get access to wi-fi at jnu": "students connect to the campus wi-fi using login credentials provided by the university.",
    "how do students book tickets for travel at jnu": "students book travel tickets online or through agents near the campus shopping complex.",
    "how do students get help during emergencies at jnu": "students can call the campus security or go to the health center in case of emergencies.",
    "how do students withdraw cash at jnu": "students use ATMs located near the shopping complex and the administrative building.",
    "how do students keep up with classes at jnu": "students attend lectures regularly, take notes, and participate in study groups to keep up with their classes.",
    "how do students order food at jnu": "students order food from campus canteens or use food delivery apps to get food from outside restaurants.",
    "how do students manage heavy study workloads at jnu": "students manage workloads by creating study schedules, breaking tasks into smaller parts, and seeking help from peers or professors.",
    "how do students maintain their mental health at jnu": "students take breaks, talk to friends, seek counseling services, and participate in relaxing activities like yoga or meditation.",
    "how do students participate in protests at jnu": "students join protests organized by student unions or groups, often held in key areas like the administrative building or academic squares.",
    "how do students stay informed about campus events at jnu": "students stay informed through posters, emails, and social media announcements about upcoming events.",
    
    "where can i get food": "you can get food at campus canteens, dhabas, or nearby shops.",
    "where can i get water": "there are water coolers in hostels and academic buildings.",
    "where can i get tea": "you can get tea at campus dhabas or canteens.",
    "where can i get coffee": "coffee is available at canteens and dhabas on campus.",
    "where can i buy snacks": "snacks are sold at dhabas, canteens, and small shops around campus.",
    "where can i charge my phone": "you can charge your phone in your hostel room or in common areas with charging points.",
    "where can i get medicine": "you can get medicine at the campus health center or nearby pharmacies.",
    "where can i find book": "you can find books at the central library or buy them from campus shops.",
    "where can i get study materials": "study materials are available at the library or campus stationery shops.",
    "where can i make photocopies": "you can make photocopies at the printing shops near the library or academic buildings.",
    "where can i get breakfast": "breakfast is available at canteens or dhabas on campus.",
    "where can i get lunch": "lunch can be found at the campus canteens or dhabas.",
    "where can i get dinner": "dinner is served at campus canteens and dhabas.",
    "where can i buy fruits": "fruits are sold at small shops and stalls near the hostels.",
    "where can i get internet": "internet is available through campus wi-fi in hostels and academic areas.",
    "where can i do laundry": "there are laundry rooms in the hostels or you can use laundry services nearby.",
    "where can i buy clothes": "you can buy clothes at the shops near the campus or in nearby markets.",
    "where can i send a parcel": "parcels can be sent from the post office located on campus.",
    "where can i buy a notebook": "notebooks are available at the campus stationery shops or nearby stores.",
    "where can i get a haircut": "there are barbers and salons near the hostels or just outside the campus.",
    "where can i rest": "you can rest in your hostel room, library, or on the lawns.",
    "where can i meet new people": "you can meet new people at dhabas, hostels, or during campus events.",
    "where can i get help for studying": "help is available from professors, seniors, or in study groups at the library.",
    "where can i get help for mental health": "the campus counseling center offers mental health support.",
    "where can i take a walk": "you can take a walk around the scenic paths or gardens on campus.",
    "where can i play sports": "sports facilities like football fields, basketball courts, and a gym are available on campus.",
    "where can i find quiet study spots": "the library or less crowded areas on campus are good for quiet study.",
    "where can i relax in nature": "you can relax in the green areas or gardens around the campus.",
    
    "where is the library": "the library is located at the center of the campus, near the academic buildings.",
    
    "where is damodar hostel": "damodar hostel is located near the eastern side of the campus, close to the shopping complex and other student hostels.",
    
    "where is kaveri hostel": "kaveri hostel is located near the administrative block and is one of the main hostels for students.",
    "where is periyar hostel": "periyar hostel is located close to the library and is easily accessible from the academic buildings.",
    "where is ganga hostel": "ganga hostel is situated near the sports complex, offering students easy access to sports facilities.",
    "where is sabarmati hostel": "sabarmati hostel is located in the central area of the campus, near the academic and cultural centers.",
    "where is tapti hostel": "tapti hostel is located near the student activity center and is close to several campus canteens.",
    "where is jhelum hostel": "jhelum hostel is located towards the southern end of the campus, surrounded by green spaces and walking paths.",
    "where is brahmaputra hostel": "brahmaputra hostel is situated near the health center and some of the key academic departments.",
    "where is chandrabhaga hostel": "chandrabhaga hostel is located near the eastern side of the campus, adjacent to other men's hostels.",
    "where is sutlej hostel": "sutlej hostel is close to the administrative building and within walking distance to the campus canteens."
    ,"default": "I'm not sure how to respond to that. Can you ask something else?"
};

 
function createMessage(content, type) {
    const messageDiv = document.createElement('div');
    messageDiv.classList.add('message', type);
    const p = document.createElement('p');
    p.textContent = content;
    messageDiv.appendChild(p);
    document.getElementById('chat-box').appendChild(messageDiv);
    document.getElementById('chat-box').scrollTop = document.getElementById('chat-box').scrollHeight;
}

function sendMessage() {
    const inputElement = document.getElementById('user-input');
    const userMessage = inputElement.value.trim().toLowerCase();
    if (userMessage) {
        createMessage(userMessage, 'user');
        inputElement.value = '';

        // Generate bot response
        const botResponse = responses[userMessage] || responses["default"];
        setTimeout(() => {
            createMessage(botResponse, 'bot');
        }, 500); // Simulate typing delay
    }
}

document.getElementById('user-input').addEventListener('keypress', function(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        sendMessage();
    }
});